// StealAnimeEgg-UI-Lab build:
//   1. builds the Roblox GUI instance tree from tools/ui/* + sample data
//   2. writes Rojo sources (src/gui/*.rbxmx, generated Luau modules)
//   3. writes browser-preview data (preview/data/*)
//   4. runs `rojo build` to produce dist/*.rbxmx, *.rbxm, *_Demo.rbxlx (if rojo exists)
//
//   node build.js [--no-rojo]
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { I, E, toRbxmx, toJSON } = require('./lib/rbx');
const D = require('./sample-data');
const { MANIFEST } = require('./lib/components');

const ROOT = path.resolve(__dirname, '..');
const w = (rel, content) => { const f = path.join(ROOT, rel); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, content); };

const hudMod = require('./ui/hud');
const screens = [];
const tryReq = (m) => { try { return require(m); } catch (e) { if (e.code === 'MODULE_NOT_FOUND' && e.message.includes(m.replace('./', ''))) return null; throw e; } };
const menus = tryReq('./ui/menus');
const preview = tryReq('./ui/preview-panel');

// Top-level children of the ScreenGui, in paint order.
const top = [
  hudMod.hud(D), hudMod.hatchWidget(D), hudMod.eggCarry(D), hudMod.backdrop(), hudMod.nav(),
  ...(menus ? menus.all(D) : []),
  ...(preview ? [preview.panel(D)] : []),
];
const SCREEN_PROPS = { ResetOnSpawn: false, ZIndexBehavior: E('Sibling'), IgnoreGuiInset: true, ScreenInsets: E('DeviceSafeInsets'), DisplayOrder: 5 };
const screenGui = I('ScreenGui', { Name: 'StealAnimeEggUI', ...SCREEN_PROPS }, ...top);

// Deterministic paint order: Roblox (ZIndexBehavior.Sibling) sorts siblings by
// ZIndex; ties are not something to rely on after Rojo/Studio round-trips.
// Re-rank every GuiObject's siblings by (declared ZIndex, declaration order).
const GUI = new Set(['Frame', 'TextLabel', 'TextButton', 'ImageLabel', 'ImageButton', 'ScrollingFrame', 'ViewportFrame']);
(function normalizeZ(inst) {
  const g = inst.children.filter((c) => GUI.has(c.cls));
  g.map((c, i) => ({ c, i, z: c.props.ZIndex ?? 1 })).sort((a, b) => a.z - b.z || a.i - b.i).forEach((e, rank) => { e.c.props.ZIndex = rank + 1; });
  inst.children.forEach(normalizeZ);
})(screenGui);

// ----------------------------------------------------------- Rojo sources
fs.rmSync(path.join(ROOT, 'src/gui'), { recursive: true, force: true });
for (const t of top) w(`src/gui/${t.name}.rbxmx`, toRbxmx([t]));

// Rojo package project: ScreenGui root + one model file per top-level frame + scripts
const pkg = {
  name: 'StealAnimeEggUI',
  tree: {
    $className: 'ScreenGui',
    $properties: { ResetOnSpawn: false, ZIndexBehavior: 'Sibling', IgnoreGuiInset: true, ScreenInsets: 'DeviceSafeInsets', DisplayOrder: 5 },
    ...Object.fromEntries(top.map((t) => [t.name, { $path: `src/gui/${t.name}.rbxmx` }])),
    LabScripts: { $path: 'src/client' },
  },
};
w('package.project.json', JSON.stringify(pkg, null, 2) + '\n');

// ------------------------------------------------------ generated Luau data
function luau(v, ind = '') {
  const n = ind + '\t';
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'string') return JSON.stringify(v);
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) return v.length ? `{\n${v.map((x) => n + luau(x, n)).join(',\n')},\n${ind}}` : '{}';
  const ks = Object.keys(v);
  return `{\n${ks.map((k) => `${n}${/^[A-Za-z_][A-Za-z0-9_]*$/.test(k) ? k : `[${JSON.stringify(k)}]`} = ${luau(v[k], n)}`).join(',\n')},\n${ind}}`;
}
w('src/client/PREVIEW_SampleData.lua', `--!strict
-- ==========================================================================
--  SAMPLE / PREVIEW DATA ONLY - NOT PRODUCTION GAMEPLAY, NOT A GAME ECONOMY.
--  GENERATED by tools/build.js from tools/sample-data.js. Do not hand-edit.
-- ==========================================================================
return ${luau(D)}
`);
const assetMap = {};
for (const [k, m] of Object.entries(MANIFEST.images)) assetMap[k] = m.atlas ? { atlas: m.atlas, offset: m.offset, size: m.size } : { image: m.standalone, size: m.size };
w('src/client/AssetManifest.lua', `--!strict
-- GENERATED by tools/render-art.js + tools/build.js. Maps AssetKey -> atlas rect.
-- Upload the PNGs listed in AssetIds.lua and paste their ids there.
return {
\tatlases = ${luau(Object.keys(MANIFEST.atlases), '\t')},
\timages = ${luau(assetMap, '\t')},
}
`);

// ------------------------------------------------------------ preview data
const pv = (rel, s) => w(`preview/data/${rel}`, s);
pv('ui-tree.js', `// GENERATED by tools/build.js\nwindow.UI_TREE = ${JSON.stringify(toJSON(screenGui))};\n`);
pv('sample.js', `// GENERATED – SAMPLE DATA ONLY\nwindow.SAMPLE = ${JSON.stringify(D)};\n`);
const assets = {};
for (const a of Object.keys(MANIFEST.atlases)) assets[a] = 'data:image/png;base64,' + fs.readFileSync(path.join(ROOT, MANIFEST.atlases[a].file)).toString('base64');
for (const [k, m] of Object.entries(MANIFEST.images)) if (m.standalone) assets[k] = 'data:image/png;base64,' + fs.readFileSync(path.join(ROOT, m.file)).toString('base64');
pv('assets.js', `// GENERATED – atlas PNGs as data URIs so preview/index.html works from file://\nwindow.ASSET_MANIFEST = ${JSON.stringify(MANIFEST)};\nwindow.ASSET_DATA = ${JSON.stringify(assets)};\n`);
const fontDir = path.join(__dirname, 'node_modules/@fontsource');
const f64 = (p) => fs.readFileSync(path.join(fontDir, p)).toString('base64');
pv('fonts.css', `/* GENERATED – Luckiest Guy + Fredoka (SIL OFL) embedded for offline preview */
@font-face{font-family:'Luckiest Guy';font-weight:400;src:url(data:font/woff2;base64,${f64('luckiest-guy/files/luckiest-guy-latin-400-normal.woff2')}) format('woff2');}
@font-face{font-family:'Fredoka';font-weight:600;src:url(data:font/woff2;base64,${f64('fredoka/files/fredoka-latin-600-normal.woff2')}) format('woff2');}
`);

// --------------------------------------------------------------- Rojo build
if (!process.argv.includes('--no-rojo')) {
  let rojo = 'rojo';
  try { execFileSync(rojo, ['--version']); } catch { rojo = null; }
  if (!rojo) { console.warn('rojo not found – skipping dist/ build'); }
  else {
    fs.mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
    const run = (proj, out) => { execFileSync(rojo, ['build', proj, '-o', out], { cwd: ROOT, stdio: 'inherit' }); };
    run('package.project.json', 'dist/StealAnimeEgg_UI_Lab.rbxmx');
    run('package.project.json', 'dist/StealAnimeEgg_UI_Lab.rbxm');
    run('default.project.json', 'dist/StealAnimeEgg_UI_Lab_Demo.rbxlx');
  }
}
// ------------------------------------------------ hierarchy outline for docs
const outline = [];
(function walk(n, d, p) {
  const mods = n.children.filter((c) => /^UI/.test(c.cls)).map((c) => c.cls.replace(/^UI/, '')).join(',');
  const a = Object.keys(n.attrs).filter((k) => k !== 'AssetKey').map((k) => `${k}=${n.attrs[k]}`).join(' ');
  const key = n.attrs.AssetKey ? ` img:${n.attrs.AssetKey}` : '';
  if (!/^UI/.test(n.cls)) outline.push(`${'  '.repeat(d)}${n.name} [${n.cls}]${mods ? ` {${mods}}` : ''}${key}${a ? `  <${a}>` : ''}`);
  const limit = /^(Card_|Unit_|EggCard_|Row_|Drop_|Cash\d|Boost\d|Chip_)/.test(n.name) && p ? 0 : 1;
  if (d < 9 && limit) n.children.filter((c) => !/^UI/.test(c.cls)).forEach((c, i, arr) => {
    // collapse repeated siblings after the first two
    const rep = /^(Card_|Unit_|EggCard_|Row_|Drop_|Cash\d|Boost\d|Chip_|Pip\d|Slot\d|Rivet\d|Special\d|Item\d|Perk\d)/.test(c.name);
    const firstOfKind = arr.findIndex((x) => x.name.replace(/[_\d].*$/, '') === c.name.replace(/[_\d].*$/, '')) === i;
    if (!rep || firstOfKind) walk(c, d + 1, rep && !firstOfKind);
    else if (arr.filter((x) => x.name.replace(/[_\d].*$/, '') === c.name.replace(/[_\d].*$/, '')).indexOf(c) === 1) outline.push(`${'  '.repeat(d + 1)}... (${c.name.replace(/[_\d].*$/, '')}* repeated)`);
  });
})(screenGui, 0, false);
w('docs/UI_HIERARCHY_TREE.txt', `GENERATED by tools/build.js - instance outline of StealAnimeEggUI\n{..} = UI modifiers (Corner, Stroke, Gradient, ListLayout, ...), img: = AssetKey, <..> = attributes\nRepeated cards/rows are collapsed after the first instance.\n\n${outline.join('\n')}\n`);

let count = 0; (function c(n) { count++; n.children.forEach(c); })(screenGui);
console.log(`built ScreenGui with ${count} instances (${top.length} top-level frames)`);
