// Production UI build: tools/prod/ui.js -> game/ui/SAE_UI.rbxmx (ScreenGui "SAE_UI").
// The Lune assembler (game/assembler/build.luau) inserts it into StarterGui.
//   node build-prod.js
const fs = require('fs');
const path = require('path');
const { I, E, toRbxmx, toJSON } = require('./lib/rbx');
const { build } = require('./prod/ui');

const ROOT = path.resolve(__dirname, '..');
const w = (rel, content) => { const f = path.join(ROOT, rel); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, content); };

const top = build();
const screenGui = I('ScreenGui', {
  Name: 'SAE_UI', ResetOnSpawn: false, ZIndexBehavior: E('Sibling'), IgnoreGuiInset: true, ScreenInsets: E('DeviceSafeInsets'), DisplayOrder: 5,
  $attrs: { Source: 'UI Lab design system (tools/prod/ui.js)', Build: 'FullProduction_OwnerReview_v01' },
}, ...top);

// deterministic paint order (same pass as the UI Lab build)
const GUI = new Set(['Frame', 'TextLabel', 'TextButton', 'ImageLabel', 'ImageButton', 'ScrollingFrame', 'ViewportFrame']);
(function normalizeZ(inst) {
  const g = inst.children.filter((c) => GUI.has(c.cls));
  g.map((c, i) => ({ c, i, z: c.props.ZIndex ?? 1 })).sort((a, b) => a.z - b.z || a.i - b.i).forEach((e, rank) => { e.c.props.ZIndex = rank + 1; });
  inst.children.forEach(normalizeZ);
})(screenGui);

// no sample data may leak into production
const banned = /SAMPLE|PREVIEW|Rengoku Lv|Demo/;
(function scan(n, p) {
  const t = n.props.Text;
  if (typeof t === 'string' && banned.test(t)) throw new Error(`demo text in production UI at ${p}: ${t}`);
  n.children.forEach((c) => scan(c, `${p}.${c.name}`));
})(screenGui, 'SAE_UI');

w('game/ui/SAE_UI.rbxmx', toRbxmx([screenGui]));
w('tools/prod/review/ui-tree.js', `// GENERATED by tools/build-prod.js\nwindow.UI_TREE = ${JSON.stringify(toJSON(screenGui))};\n`);
let count = 0; (function c(n) { count++; n.children.forEach(c); })(screenGui);
console.log(`built SAE_UI with ${count} instances (${top.length} top-level) -> game/ui/SAE_UI.rbxmx`);
