"""
Generate Roblox Studio staging data modules from the Blender export manifests.

  python3 tools/studio/gen_world_data.py [repo_root]

Writes tools/studio/world_data/<WorldId>.lua. Each module returns the expected pieces of one world (name, size in
studs, world-local position, Roblox Material, Color, Transparency, CanCollide, layer), plus the VFX anchors (egg
anchors included) and the invisible gameplay colliders. StagingValidateRestore.lua uses it inside Studio.

Sources: the committed per-world manifests, except Solo Leveling, which uses the recovered export
(art/integration/world-import-v02/08_SoloLeveling/pieces/manifest.json) because the committed export had three
FBX filename collisions.
"""
import json
import os
import sys

REPO = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
WORLDS = [
    ("MHA", "art/exports/worlds/02_MHA/manifest.json"),
    ("DragonBall", "art/exports/worlds/03_DragonBall/manifest.json"),
    ("OnePiece", "art/exports/worlds/04_OnePiece/manifest.json"),
    ("Naruto", "art/exports/worlds/05_Naruto/manifest.json"),
    ("Bleach", "art/exports/worlds/06_Bleach/manifest.json"),
    ("JJK", "art/exports/worlds/07_JJK/manifest.json"),
    ("SoloLeveling", "art/integration/world-import-v02/08_SoloLeveling/pieces/manifest.json"),
]


def v3(t):
    return "Vector3.new(%s, %s, %s)" % tuple(repr(round(float(c), 3)) for c in t)


def main():
    out_dir = os.path.join(REPO, "tools", "studio", "world_data")
    os.makedirs(out_dir, exist_ok=True)
    for world, rel in WORLDS:
        m = json.load(open(os.path.join(REPO, rel)))
        L = [f"-- GENERATED by tools/studio/gen_world_data.py from {rel}. Do not edit by hand.",
             "-- Positions are world-local studs (world entrance at local Z = 0); add the world's route offset.", "return {",
             f'\tworld = "{world}",', f'\tsource = "{rel}",', "\timportScale = 0.01, -- Studio 3D Importer scale for these FBX exports",
             f"\tpieceCount = {len(m['modules'])},", "\tpieces = {"]
        for p in m["modules"]:
            L.append(f'\t\t{{ name = "{p["module"]}", size = {v3(p["sizeStuds"])}, position = {v3(p["robloxPosition"])}, '
                     f'material = "{p["robloxMaterial"]}", color = "{p["color"]}", transparency = {p["transparency"]}, '
                     f'canCollide = {str(p["canCollide"]).lower()}, layer = "{p["layer"]}", triangles = {p["triangles"]} }},')
        L.append("\t},")
        L.append("\tanchors = {")
        for a in m["anchors"]:
            kind = a["kind"].replace('"', "'")
            L.append(f'\t\t{{ name = "{a["name"]}", position = {v3(a["robloxPosition"])}, kind = "{kind}" }},')
        L.append("\t},")
        L.append("\tcolliders = {")
        for c in m.get("colliders", []):
            L.append(f'\t\t{{ name = "{c["name"]}", position = {v3(c["robloxPosition"])}, size = {v3(c["sizeStuds"])} }},')
        L.append("\t},")
        eggs = [a["name"] for a in m["anchors"] if a["name"].startswith("VFX_EggNest")]
        L.append(f"\teggAnchorCount = {len(eggs)},")
        L.append("}")
        with open(os.path.join(out_dir, f"{world}.lua"), "w") as f:
            f.write("\n".join(L) + "\n")
        print(f"{world}: {len(m['modules'])} pieces, {len(m['anchors'])} anchors ({len(eggs)} egg), {len(m.get('colliders', []))} colliders")


if __name__ == "__main__":
    main()
